name: ahmad_pro
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_launcher_icons: "^0.8.0"
  font_awesome_flutter: ^8.11.0
  flutter_datetime_picker: ^1.4.0
  flutter_time_date_picker: ^0.0.2
  carousel_slider: ^3.0.0
  flutter_svg:
  connectivity: ^0.4.3+1
  flutter_spinkit: "^4.1.2"
  intl_phone_field: ^1.4.2
  http:
  equatable: ^1.2.6
  dio: ^3.0.10
  html:
  flutter_html:
  path:
  timeago: ^2.0.29
  firebase_messaging:
  webview_flutter: 
  sqflite:
  flutter_staggered_grid_view: ^0.3.3
  cached_network_image: ^2.5.0
  code_fields:
  url_launcher: ^5.0.0
  smooth_star_rating: ^1.1.1
  flutter_slidable: ^0.5.7
  chewie: ^0.12.1+1
  video_player: ^1.0.1
  geolocator:
  youtube_player_flutter: 7.0.0+7
  shared_preferences:
  provider:
  change_app_package_name:
  image_picker:
  image_cropper:
  flutter_youtube_vimeo:
  vimeoplayer_trinity:
  vimeoplayer:
  # audioplayers:
  assets_audio_player:
  
  # gx_file_picker: 1.9.0+2
  my_fatoorah:
  # purchases_flutter: 2.0.3
  plugin_platform_interface: ^2.0.0
  in_app_purchase: ^0.3.5+1
  fluttertoast:
  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/images/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/icons/
    - lib/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
